# Generated by Django 3.2.2 on 2021-05-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0002_rename_organizer_email_event_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
