# Generated by Django 3.2.2 on 2021-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0003_remove_event_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
