# Generated by Django 3.2.2 on 2021-05-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0004_auto_20210515_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='connect_app.Tag'),
        ),
    ]
